# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ac1d702a41af89a52ef7d98e12e860b8bb224392520bf7e7a4b094e620fed41e616e6803a4e417c9129fc9b676ae0cdfaa0f06fba28effa52b668083d3b7a9

test:
  secret_key_base: 474927bb81ec7821b9804e5fb2b4a56e2fbb39d7b1c5352c9e0e64935867a9797756edebae48c795d6a640d9c3fa3745dd6c0f662cbfd955bca64023bcd4465d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
